- name: Creating node_exporter user group
  group: name="node_exporter"
  become: true

- name: Creating node exporter user
  user:
    name: "node_exporter"
    group: "node_exporter"
    system: yes
    shell: "/sbin/nologin"
    comment: "node_exporter nologin User"
    createhome: "no"
    state: present

- name: Install node_exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy node_exporter file to bin
  copy:
    src: "/tmp/node_exporter-1.3.1.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "node_exporter"
    group: "node_exporter"
    remote_src: yes
    mode: 0755

- name: Delete node_exporter tmp folder
  file:
    path: '/tmp/node_exporter-1.3.1.linux-amd64'
    state: absent

- name: Ensure system file exists first
  file:
    path: '/usr/lib/systemd/system'
    state: directory

- name: Copy systemd init file
  copy:
    src: node-exporter.service
    dest: /usr/lib/systemd/system/node_exporter.service

- name: Reload daemon set
  systemd:
    name: node_exporter.service
    state: reloaded
    daemon-reload: yes

- name: Start node_exporter service
  systemd:
    name: node_exporter.service
    state: started
    enabled: yes

- name: Check if node exporter emits metrics
  uri:
    url: http://127.0.0.1:9100/metrics
    method: GET
    status_code: 200

